# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=6)),
                ('photo', models.CharField(max_length=50)),
                ('contact_name', models.CharField(max_length=30)),
                ('contact_phone', models.CharField(max_length=15)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accomodation_length', models.CharField(choices=[('ST', 'Short Term'), ('LT', 'Long Term')], default='ST', max_length=2)),
                ('tenant_type', models.CharField(choices=[('HL', 'Homeless'), ('AR', 'At Risk'), ('YT', 'Youth')], default='HL', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=6)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('serv_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='availableservices',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HackApp.House'),
        ),
        migrations.AddField(
            model_name='availableservices',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HackApp.Service'),
        ),
    ]
