# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HackApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailableServices',
            new_name='AvailableService',
        ),
    ]
