# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackApp', '0003_auto_20170603_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='weight',
            field=models.DecimalField(decimal_places=6, default=0.1, max_digits=9),
            preserve_default=False,
        ),
    ]
